server:
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '4'
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:5432/tripf
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'

  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 8MB  # 파일 용량 제한
      max-request-size: 128MB # 전체 최대 크기 용량 제한

    cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: mail.tripf@gmail.com
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

jwt:
  secret: ${JWT_SECRET}
  expiry-millis: 300000 # 토큰 만료시간 (밀리초)

google:
  api:
    key: ${GOOGLE_API_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucketName: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false