server:
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '4'
    username: <<db username>>
    url: jdbc:postgresql://<<db url>>:<<port>>/<<database>>
    password: <<db password>>
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create