server:
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '4'
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:5432/tripf
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'

jwt:
  secret: ${JWT_SECRET}
  expiry-millis: 300000 # 토큰 만료시간 (밀리초)